#Minecraft server properties
#Thu Dec 19 00:37:31 UTC 2024
allow-flight=false
allow-nether=false
announce-player-achievements=false
broadcast-console-to-ops=true
debug=false
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=false
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=DEFAULT
max-build-height=256
max-players=2000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=-1
online-mode=false
op-permission-level=4
player-idle-timeout=0
pvp=true
resource-pack=
resource-pack-hash=
server-ip=
server-name=Paid Premade
server-port=25565
snooper-enabled=true
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
spawn-protection=0
use-native-transport=true
view-distance=10
white-list=false
